#!/bin/bash
set -e

sed -i "s/{ code: 'mock-wallet', display: 'Mock (Caution\!)', class: WALLET, cryptos: ALL_CRYPTOS },/{ code: 'mock-wallet', display: 'Mock (Caution\!)', class: WALLET, cryptos: ALL_CRYPTOS, dev: true },/g" $(npm -g root)/lamassu-server/lib/new-admin/config/accounts.js

supervisorctl restart lamassu-server lamassu-admin-server &>/dev/null

echo
echo "Mock Wallet option removed, however..."
echo
echo "You must now set the wallet(s) back to bitcoind, geth, etc. in your admin – or the mock wallet will still be active!"
echo
