#!/usr/bin/env bash

mkdir -p /var/lock/lamassu-eth-pending-sweep &>/dev/null

cd $(npm root -g)/lamassu-server &>/dev/null

curl -o bin/lamassu-eth-sweep-to-new-wallet https://raw.githubusercontent.com/lamassu/lamassu-server/v8.0.1/bin/lamassu-eth-sweep-to-new-wallet &>/dev/null

chmod +x bin/lamassu-eth-sweep-to-new-wallet &>/dev/null

echo
node bin/lamassu-eth-sweep-to-new-wallet
echo

echo "Restarting services..."
sleep 5s
superviorctl restart lamassu-server lamassu-admin-server &>/dev/null
echo

cd ~

echo "Done! Please reach out to support with a screenshot of the above, and for steps to complete the upgrade."
echo
