#!/usr/bin/env bash
set -e

EMAIL_ADDRESS=$1
if [ ! $# -eq 1 ]; then
  echo "bills-log-unencrypted <email_address>"
  exit 1
elif [[ ! $EMAIL_ADDRESS =~ .+@.+\..+ ]]; then
  echo "Please enter a valid email address."
  echo
  echo "bills-log-unencrypted <email_address>"
  exit 1
fi

if [ $(dpkg-query -W -f='${Status}' mutt 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  echo "Mutt not installed. Installing..."
  DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes mutt >/dev/null;
fi

BILLS_FILE=/tmp/bills-$HOSTNAME-$(date -u "+%Y-%m-%d_%H-%M-%S").csv
su - postgres -c "psql \"lamassu\" -Atc \"COPY bills to '$BILLS_FILE' WITH CSV HEADER\""
export EMAIL="Bills Log <$EMAIL_ADDRESS>"
echo "Attached is your unencrypted bills log." | mutt -s "Unencrypted bills log from $HOSTNAME" -a $BILLS_FILE -- $EMAIL_ADDRESS
rm $BILLS_FILE
echo "Bills log sent to $EMAIL_ADDRESS. If it doesn't appear, check your spam folder."
