#!/usr/bin/env bash
set -e

EMAIL_ADDRESS=$1
if [ ! $# -eq 1 ]; then
  echo "cash-out-log <email_address>"
  exit 1
elif [[ ! $EMAIL_ADDRESS =~ .+@.+\..+ ]]; then
  echo "Please enter a valid email address."
  echo
  echo "cash-out-log <email_address>"
  exit 1
fi

if [ $(dpkg-query -W -f='${Status}' mutt 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  echo "Mutt not installed. Installing..."
  DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes mutt >/dev/null;
fi

CASHOUT_FILE=/tmp/cash-out-$HOSTNAME-$(date -u "+%Y-%m-%d_%H-%M-%S").csv
su - postgres -c "psql \"lamassu\" -Atc \"COPY cash_out_txs to '$CASHOUT_FILE' WITH CSV HEADER\""
gpg --batch --trust-model always -e -r $EMAIL_ADDRESS $CASHOUT_FILE
rm $CASHOUT_FILE
export EMAIL="Cash-out Log <$EMAIL_ADDRESS>"
echo "Attached is your encrypted cash-out log." | mutt -s "Encrypted cash-out log from $HOSTNAME" -a $CASHOUT_FILE.gpg -- $EMAIL_ADDRESS
rm $CASHOUT_FILE.gpg
echo "Cash-out log sent to $EMAIL_ADDRESS. If it doesn't appear, check your spam folder."
