#!/usr/bin/env bash
set -e

EMAIL_ADDRESS=$1
if [ ! $# -eq 1 ]; then
  echo "cash-out-actions <email_address>"
  exit 1
elif [[ ! $EMAIL_ADDRESS =~ .+@.+\..+ ]]; then
  echo "Please enter a valid email address."
  echo
  echo "cash-out-actions <email_address>"
  exit 1
fi

if [ $(dpkg-query -W -f='${Status}' mutt 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  echo "Mutt not installed. Installing..."
  DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes mutt >/dev/null;
fi

CASHOUTACT_FILE=/tmp/cash-out-act-$HOSTNAME-$(date -u "+%Y-%m-%d_%H-%M-%S").csv
su - postgres -c "psql \"lamassu\" -Atc \"COPY cash_out_actions to '$CASHOUTACT_FILE' WITH CSV HEADER\""
gpg --batch --trust-model always -e -r $EMAIL_ADDRESS $CASHOUTACT_FILE
rm $CASHOUTACT_FILE
export EMAIL="Cash-out Actions Log <$EMAIL_ADDRESS>"
echo "Attached is your encrypted cash-out actions log." | mutt -s "Encrypted cash-out actions log from $HOSTNAME" -a $CASHOUTACT_FILE.gpg -- $EMAIL_ADDRESS
rm $CASHOUTACT_FILE.gpg
echo "Cash-out actions log sent to $EMAIL_ADDRESS. If it doesn't appear, check your spam folder."
