#!/usr/bin/env bash
set -e

EMAIL_ADDRESS=$1
if [ ! $# -eq 1 ]; then
  echo "cash-in-unencrypted <email_address>"
  exit 1
elif [[ ! $EMAIL_ADDRESS =~ .+@.+\..+ ]]; then
  echo "Please enter a valid email address."
  echo
  echo "cash-in-unencrypted <email_address>"
  exit 1
fi

if [ $(dpkg-query -W -f='${Status}' mutt 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  echo "Mutt not installed. Installing..."
  DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes mutt >/dev/null;
fi

CASHIN_FILE=/tmp/cash-in-$HOSTNAME-$(date -u "+%Y-%m-%d_%H-%M-%S").csv
su - postgres -c "psql \"lamassu\" -Atc \"COPY cash_in_txs to '$CASHIN_FILE' WITH CSV HEADER\""
export EMAIL="Cash-in Log <$EMAIL_ADDRESS>"
echo "Attached is your unencrypted cash-in log." | mutt -s "Unencrypted cash-in log from $HOSTNAME" -a $CASHIN_FILE -- $EMAIL_ADDRESS
rm $CASHIN_FILE
echo "Cash-in log sent to $EMAIL_ADDRESS. If it doesn't appear, check your spam folder."
