#!/usr/bin/env bash
set -e

NAME=$1
if [ ! $# -eq 1 ]; then
  echo "send-server-log <name>"
  exit 1
elif [[ ! $NAME =~ . ]]; then
  echo "Please enter your name"
  echo
  echo "send-server-log <name>"
  exit 1
fi

SERVER_LOG_ARCHIVE=/tmp/lamassu-server-log_$HOSTNAME.tar.bz2
echo "$(supervisorctl status)" > /tmp/status.log
echo "$(cat $(npm root -g)/lamassu-server/package.json | grep "lamassu-server@")" >> /tmp/status.log
echo "$(su - postgres -c "psql \"lamassu\" -x -Atc \"select device_time,device_id,note from machine_events ORDER BY created DESC LIMIT 1000\"")" > /tmp/machineactions.log
echo "$(tail -2500 /var/log/supervisor/lamassu-server.err.log)" > /tmp/lamassu-server.err.short.log
echo "$(tail -2500 /var/log/supervisor/lamassu-server.out.log)" > /tmp/lamassu-server.out.short.log
tar -cvjf $SERVER_LOG_ARCHIVE /tmp/lamassu-server.*.log /tmp/status.log /tmp/machineactions.log

timestamp() {
  date +"%Y%m%d-%H%M%S"
}

HOST=165.227.82.206
USER='ftpuser'
REMOTEPATH=/home/ftpuser/ftp/files
KEYPATH=/etc/lamassu/keys/lamassu-log-server.key
scp -i $KEYPATH -oStrictHostKeyChecking=no $SERVER_LOG_ARCHIVE $USER@$HOST:$REMOTEPATH/$NAME-$HOSTNAME-$(timestamp).tar.bz2

rm $SERVER_LOG_ARCHIVE
echo "Server logs sent to our support server."
