#!/usr/bin/env bash
set -e

NAME=$1
if [ ! $# -eq 1 ]; then
  echo "send-migration-info <name>"
  exit 1
elif [[ ! $NAME =~ . ]]; then
  echo "Please enter your name"
  echo
  echo "send-migration-info <name>"
  exit 1
fi

TABLE_LOG_DIR=/tmp/ftp-logs/migrations
TABLE_LOG_ARCHIVE=$TABLE_LOG_DIR/lamassu-migration-info_$HOSTNAME.tar.bz2
mkdir -p $TABLE_LOG_DIR

echo
echo "Compiling table descriptions and migration history, this may take a moment..."

# Main transaction tables
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"\\d cash_in_txs\"")" >> $TABLE_LOG_DIR/table-columns-cash_in_txs.log
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"\\d bills\"")" >> $TABLE_LOG_DIR/table-columns-bills.log
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"\\d cash_out_txs\"")" >> $TABLE_LOG_DIR/table-columns-cash_out_txs.log
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"\\d cash_out_actions\"")" >> $TABLE_LOG_DIR/table-columns-cash_out_actions.log

# Other recently migrated tables
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"\\d customers\"")" >> $TABLE_LOG_DIR/table-columns-customers.log
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"\\d blacklist\"")" >> $TABLE_LOG_DIR/table-columns-blacklist.log
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"\\d machine_pings\"")" >> $TABLE_LOG_DIR/table-columns-machine_pings.log

# History of migration scripts run
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"SELECT * FROM migrations;\"")" > $TABLE_LOG_DIR/migrations-history.log

# Recent server logs for good measure
echo "$(tail -250000 /var/log/supervisor/lamassu-server.err.log)" > $TABLE_LOG_DIR/lamassu-server.err.short.log
echo "$(tail -250000 /var/log/supervisor/lamassu-server.out.log)" > $TABLE_LOG_DIR/lamassu-server.out.short.log
echo "$(tail -250000 /var/log/supervisor/lamassu-admin-server.err.log)" > $TABLE_LOG_DIR/lamassu-admin-server.err.short.log

tar -cvjf $TABLE_LOG_ARCHIVE $TABLE_LOG_DIR/*.log &>/dev/null

timestamp() {
  date +"%Y%m%d-%H%M%S"
}

HOST=165.227.82.206
USER='ftpuser'
REMOTEPATH=/home/ftpuser/ftp/files
KEYPATH=/etc/lamassu/keys/lamassu-log-server.key
scp -i $KEYPATH -oStrictHostKeyChecking=no -P 22 $TABLE_LOG_ARCHIVE $USER@$HOST:$REMOTEPATH/migrations-$NAME-$HOSTNAME-$(timestamp).tar.bz2 &>/dev/null

rm $TABLE_LOG_DIR/*

echo
echo "Done. Table descriptions and migration history sent to our support server."
echo
