#!/usr/bin/env bash

NAME=$1
if [ ! $# -eq 1 ]; then
  echo "send-postgres <name>"
  exit 1
elif [[ ! $NAME =~ . ]]; then
  echo "Please enter your name"
  echo
  echo "send-postgres <name>"
  exit 1
fi

echo
echo "Compiling config records..."
echo

CONFIG_RECORD=/tmp/postgres-info/
CONFIG_ARCHIVE=/tmp/postgres-config_$HOSTNAME.tar.bz2

# clean up existing logs
rm -r $CONFIG_RECORD &>/dev/null
rm $CONFIG_ARCHIVE &>/dev/null

# export config info

mkdir -p /tmp/postgres-info/
systemctl list-units | grep '^\s*postgresql' >> /tmp/postgres-info/systemctl.txt
journalctl -u postgresql@12-main >> /tmp/postgres-info/journalctl.txt
grep '"postgresql"' /etc/lamassu/lamassu.json | sed 's|:[^:@]\+@|:***@|;' >> /tmp/postgres-info/lamassu.support.json
cp /var/log/postgresql/*.log /tmp/postgres-info/postgresql.support.log
cp /etc/postgresql/*/*/postgresql.conf /tmp/postgres-info/postgresql.support.conf
cp /etc/postgresql/*/*/pg_hba.conf /tmp/postgres-info/pg_hba.support.conf

# compress it
tar -cvjf $CONFIG_ARCHIVE $CONFIG_RECORD &>/dev/null

timestamp() {
  date +"%Y%m%d-%H%M%S"
}

echo "Uploading config logs..."
echo

HOST=165.227.82.206
USER='ftpuser'
REMOTEPATH=/home/ftpuser/ftp/files
KEYPATH=/etc/lamassu/keys/lamassu-log-server.key
scp -i $KEYPATH -oStrictHostKeyChecking=no -P 22 $CONFIG_ARCHIVE $USER@$HOST:$REMOTEPATH/$NAME-$HOSTNAME-$(timestamp).tar.bz2 &>/dev/null

# clean up logs
rm -r $CONFIG_RECORD &>/dev/null
rm $CONFIG_ARCHIVE &>/dev/null

echo "Config logs sent to our support server. Please let us know."
echo
