#!/usr/bin/env bash
set -e

NAME=$1
if [ ! $# -eq 1 ]; then
  echo "send-server-log <name>"
  exit 1
elif [[ ! $NAME =~ . ]]; then
  echo "Please enter your name"
  echo
  echo "send-server-log <name>"
  exit 1
fi
echo "Compiling server and machine logs, this may take a couple of minutes..."
SERVER_LOG_ARCHIVE=/tmp/lamassu-server-log_$HOSTNAME.tar.bz2
echo "$(supervisorctl status)" > /tmp/status.log
echo "$(cat $(npm root -g)/lamassu-server/package.json | grep "lamassu-server@")" >> /tmp/status.log
echo "$(df -h)" >> /tmp/status.log
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"select device_id, name from devices\"")" >> /tmp/devices.log
echo "$(su - postgres -c "psql \"lamassu\" -Atc \"SELECT * FROM (SELECT ROW_NUMBER() OVER (PARTITION BY device_id ORDER BY timestamp desc) AS r, t.log_level, timestamp, t.message, (select devices.name from devices where devices.device_id = t.device_id), t.device_id FROM logs t) x WHERE x.r <= 100000;\"")" > /tmp/machineactions.log
echo "$(tail -250000 /var/log/supervisor/lamassu-server.err.log)" > /tmp/lamassu-server.err.short.log
echo "$(tail -250000 /var/log/supervisor/lamassu-server.out.log)" > /tmp/lamassu-server.out.short.log
echo "$(tail -250000 /var/log/supervisor/lamassu-admin-server.err.log)" > /tmp/lamassu-admin-server.err.short.log
tar -cvjf $SERVER_LOG_ARCHIVE /tmp/*.log 

timestamp() {
  date +"%Y%m%d-%H%M%S"
}

HOST=165.227.82.206
USER='ftpuser'
REMOTEPATH=/home/ftpuser/ftp/files
KEYPATH=/etc/lamassu/keys/lamassu-log-server.key
scp -i $KEYPATH -oStrictHostKeyChecking=no -P 22 $SERVER_LOG_ARCHIVE $USER@$HOST:$REMOTEPATH/$NAME-$HOSTNAME-$(timestamp).tar.bz2

rm $SERVER_LOG_ARCHIVE
echo "Server logs sent to our support server."
