#!/usr/bin/env bash
set -e

EMAIL_ADDRESS=$1
if [ ! $# -eq 1 ]; then
  echo "trades-log <email_address>"
  exit 1
elif [[ ! $EMAIL_ADDRESS =~ .+@.+\..+ ]]; then
  echo "Please enter a valid email address."
  echo
  echo "trades-log <email_address>"
  exit 1
fi

if [ $(dpkg-query -W -f='${Status}' mutt 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  echo "Mutt not installed. Installing..."
  DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes mutt >/dev/null;
fi

TRADES_FILE=/tmp/trades-$HOSTNAME-$(date -u "+%Y-%m-%d_%H-%M-%S").csv
su - postgres -c "psql \"lamassu\" -Atc \"COPY trades to '$TRADES_FILE' WITH CSV HEADER\""
gpg --batch --trust-model always -e -r $EMAIL_ADDRESS $TRADES_FILE
rm $TRADES_FILE
export EMAIL="Trades Log <$EMAIL_ADDRESS>"
echo "Attached is your encrypted trades log." | mutt -s "Encrypted trades from $HOSTNAME" -a $TRADES_FILE.gpg -- $EMAIL_ADDRESS
rm $TRADES_FILE.gpg
echo "Trades log sent to $EMAIL_ADDRESS. If it doesn't appear, check your spam folder."
